kind: ClusterSelector
apiVersion: configmanagement.gke.io/v1
metadata:
  name: cal
spec:
  selector:
    matchLabels:
      location: cal
---
kind: ClusterSelector
apiVersion: configmanagement.gke.io/v1
metadata:
  name: pek
spec:
  selector:
    matchLabels:
      location: pek
